name: CI
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  unix:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-12, macos-13]
        xeus_static_dependencies: [1]
        xeus_build_shared_lib: [0]
        include:
          - os: ubuntu-22.04
            xeus_static_dependencies: 1
            xeus_build_shared_lib: 0
          - os: ubuntu-24.04
            xeus_static_dependencies: 1
            xeus_build_shared_lib: 0

    steps:
      - uses: actions/checkout@v4

      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
          environment-name: xeus-uv
          init-shell: bash

      - name: Create build directory
        shell: bash -l {0}
        run: mkdir -p build

      - name: Configure cmake
        shell: bash -l {0}
        run: |
          cmake .. \
           -DXEUS_UV_BUILD_TESTS=ON \
           -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
           -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
           -DXEUS_UV_STATIC_DEPENDENCIES=${{ matrix.xeus_static_dependencies }} \
           -DXEUS_UV_BUILD_SHARED_LIBS=${{ matrix.xeus_build_shared_lib }}
        working-directory: build

      - name: Build
        shell: bash -l {0}
        run: make -j ${{ runner.os == 'macOS' && 3 || 4 }}
        working-directory: build

      - name: Test xeus-uv
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 4
          max_attempts: 4
          shell: bash
          command: |
            cd build/test
            ctest --output-on-failure

      - name: Install xeus-uv
        shell: bash -l {0}
        run: make install
        working-directory: build

  win:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019, windows-2022 ]

    steps:
      - uses: actions/checkout@v4

      # v1.9.0 does not automatically activate env on win
      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
          environment-name: xeus-uv
          init-shell: cmd.exe
          create-args: >-
            ninja

      - name: Make build directory
        run: mkdir build

      - name: Configure cmake
        shell: cmd /C call {0}
        run: |
          micromamba activate xeus-uv
          cmake .. ^
           -G Ninja ^
           -DCMAKE_BUILD_TYPE=Release ^
           -DXEUS_UV_BUILD_TESTS=ON ^
           -DDEPENDENCY_SEARCH_PREFIX="%CONDA_PREFIX%\Library" ^
           -DCMAKE_PREFIX_PATH="%CONDA_PREFIX%\Library" ^
           -DCMAKE_INSTALL_PREFIX="%CONDA_PREFIX%"
        working-directory: build

      - name: Build
        shell: cmd /C call {0}
        run: |
          micromamba activate xeus-uv
          set CL=/MP
          ninja install
        working-directory: build

      - name: ctest
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 4
          max_attempts: 4
          shell: cmd
          command: |
            set PATH=%CONDA_PREFIX%;%CONDA_PREFIX%\\Scripts;%CONDA_PREFIX%\\Library;%CONDA_PREFIX%\\Library\\bin;%PATH%
            cd build
            ctest --output-on-failure
